### ISSUE TITLE
development improvements

### ISSUE THREAD

**Issue by MareoRaft** [analythium/shinyproxy-demo#1]
I was able to create a docker-compose file for more rapid development of the app.  Would you like me to make a PR or something to include those improvements in this repo?

**Comment by psolymos** [comment]
Hi @MareoRaft I am curious to see what you made. Are there any other services that you created besides the Shiny app?

**Comment by MareoRaft** [comment]
It is just a `docker-compose.yml` file which allows a developer to run/develop their app locally with more convenience.

Nothing big; there are no other services.

**Comment by MareoRaft** [comment]
@psolymos Did you get a chance to look at the PR?

**Comment by psolymos** [comment]
Yes, thank you @MareoRaft , I think it is really useful.
